name: Wooo

on: repository_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          echo "Setting ref to '${{ github.event.client_payload.ref }}'"
