name: Wooo

on: repository_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.ref }}'"
