name: Wooo

on: repository_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Updating ref
        run: |
          echo "Setting ref to '${{ github.event.client_payload.ref }}'"
          sed -i -e 's/=.*/${{ github.event.client_payload.ref }}/g' dev.env
      - name: identify to github
        run: |
          git config --local user.email autobot@bar.com
          git config --local user.name Autobot
      - name: check for changes
        run: git status
      - name: stage changes
        run: git add .
      - name: commit changes
        run: git commit -m "Auto ref update"
      - name: push changes
        run: git push origin HEAD:master
          
